s = input()
s = s.replace('dz=','0')
s = s.replace('z=','0')
s = s.replace('c=','0')
s = s.replace('c-','0')
s = s.replace('d-','0')
s = s.replace('lj','0')
s = s.replace('nj','0')
s = s.replace('s=','0')
#print(s)
print(len(s))
